"""initial_schema

Revision ID: b667a1ecf225
Revises: 
Create Date: 2026-07-19 10:12:51.225490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b667a1ecf225'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatar_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('model_path', sa.String(length=255), nullable=False),
    sa.Column('preview_url', sa.String(length=255), nullable=False),
    sa.Column('voice_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avatar_configs_is_active'), 'avatar_configs', ['is_active'], unique=False)
    op.create_table('behavior_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_name', sa.String(length=255), nullable=False),
    sa.Column('intended_usage', sa.Text(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('column_count', sa.Integer(), nullable=False),
    sa.Column('contains_lingshan_records', sa.Boolean(), nullable=False),
    sa.Column('summary_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavior_summaries_dataset_name'), 'behavior_summaries', ['dataset_name'], unique=True)
    op.create_index(op.f('ix_behavior_summaries_id'), 'behavior_summaries', ['id'], unique=False)
    op.create_table('chat_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('raw_query', sa.Text(), nullable=False),
    sa.Column('normalized_query', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('sources', sa.Text(), nullable=False),
    sa.Column('hit_level', sa.String(length=50), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('input_mode', sa.String(length=20), nullable=False),
    sa.Column('text_emotion', sa.String(length=30), nullable=False),
    sa.Column('audio_emotion', sa.String(length=30), nullable=True),
    sa.Column('fused_emotion', sa.String(length=30), nullable=False),
    sa.Column('emotion_confidence', sa.Float(), nullable=False),
    sa.Column('emotion_intensity', sa.Float(), nullable=False),
    sa.Column('emotion_conflict', sa.Boolean(), nullable=False),
    sa.Column('emotion_modalities', sa.Text(), nullable=False),
    sa.Column('response_strategy', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_logs_fused_emotion'), 'chat_logs', ['fused_emotion'], unique=False)
    op.create_index(op.f('ix_chat_logs_id'), 'chat_logs', ['id'], unique=False)
    op.create_index(op.f('ix_chat_logs_normalized_query'), 'chat_logs', ['normalized_query'], unique=False)
    op.create_index(op.f('ix_chat_logs_session_id'), 'chat_logs', ['session_id'], unique=False)
    op.create_table('faq_entries',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('aliases_json', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('sources_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_blind_spots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('normalized_query', sa.String(length=500), nullable=False),
    sa.Column('raw_query_samples_json', sa.Text(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('resolution_type', sa.String(length=20), nullable=True),
    sa.Column('resolved_faq_id', sa.String(length=120), nullable=True),
    sa.Column('resolved_knowledge_id', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_blind_spots_id'), 'knowledge_blind_spots', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_blind_spots_normalized_query'), 'knowledge_blind_spots', ['normalized_query'], unique=True)
    op.create_index(op.f('ix_knowledge_blind_spots_status'), 'knowledge_blind_spots', ['status'], unique=False)
    op.create_table('knowledge_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('aliases', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_entries_id'), 'knowledge_entries', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_source'), 'knowledge_entries', ['source'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_title'), 'knowledge_entries', ['title'], unique=False)
    op.create_table('qa_cache_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('normalized_query', sa.String(length=255), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('sources', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_cache_entries_id'), 'qa_cache_entries', ['id'], unique=False)
    op.create_index(op.f('ix_qa_cache_entries_normalized_query'), 'qa_cache_entries', ['normalized_query'], unique=True)
    op.create_table('quick_topics',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_quick_topics_category'), 'quick_topics', ['category'], unique=False)
    op.create_index(op.f('ix_quick_topics_is_enabled'), 'quick_topics', ['is_enabled'], unique=False)
    op.create_table('route_templates',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('duration_label', sa.String(length=100), nullable=False),
    sa.Column('route_plan', sa.Text(), nullable=False),
    sa.Column('guide_points_json', sa.Text(), nullable=False),
    sa.Column('experiences_json', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_templates_title'), 'route_templates', ['title'], unique=False)
    op.create_table('visitor_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_log_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.String(length=20), nullable=False),
    sa.Column('reason_code', sa.String(length=50), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitor_feedbacks_chat_log_id'), 'visitor_feedbacks', ['chat_log_id'], unique=False)
    op.create_index(op.f('ix_visitor_feedbacks_created_at'), 'visitor_feedbacks', ['created_at'], unique=False)
    op.create_index(op.f('ix_visitor_feedbacks_id'), 'visitor_feedbacks', ['id'], unique=False)
    op.create_index(op.f('ix_visitor_feedbacks_is_demo'), 'visitor_feedbacks', ['is_demo'], unique=False)
    op.create_index(op.f('ix_visitor_feedbacks_rating'), 'visitor_feedbacks', ['rating'], unique=False)
    op.create_index(op.f('ix_visitor_feedbacks_session_id'), 'visitor_feedbacks', ['session_id'], unique=False)
    op.create_table('visitor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('preference_tags', sa.Text(), nullable=False),
    sa.Column('audience_type', sa.String(length=100), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitor_profiles_id'), 'visitor_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_visitor_profiles_session_id'), 'visitor_profiles', ['session_id'], unique=True)
    op.create_table('knowledge_chunks',
    sa.Column('chunk_id', sa.String(length=120), nullable=False),
    sa.Column('source_entry_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_entry_id'], ['knowledge_entries.id'], ),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index(op.f('ix_knowledge_chunks_category'), 'knowledge_chunks', ['category'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_source'), 'knowledge_chunks', ['source'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_source_entry_id'), 'knowledge_chunks', ['source_entry_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_title'), 'knowledge_chunks', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_chunks_title'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_source_entry_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_source'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_category'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_visitor_profiles_session_id'), table_name='visitor_profiles')
    op.drop_index(op.f('ix_visitor_profiles_id'), table_name='visitor_profiles')
    op.drop_table('visitor_profiles')
    op.drop_index(op.f('ix_visitor_feedbacks_session_id'), table_name='visitor_feedbacks')
    op.drop_index(op.f('ix_visitor_feedbacks_rating'), table_name='visitor_feedbacks')
    op.drop_index(op.f('ix_visitor_feedbacks_is_demo'), table_name='visitor_feedbacks')
    op.drop_index(op.f('ix_visitor_feedbacks_id'), table_name='visitor_feedbacks')
    op.drop_index(op.f('ix_visitor_feedbacks_created_at'), table_name='visitor_feedbacks')
    op.drop_index(op.f('ix_visitor_feedbacks_chat_log_id'), table_name='visitor_feedbacks')
    op.drop_table('visitor_feedbacks')
    op.drop_index(op.f('ix_route_templates_title'), table_name='route_templates')
    op.drop_table('route_templates')
    op.drop_index(op.f('ix_quick_topics_is_enabled'), table_name='quick_topics')
    op.drop_index(op.f('ix_quick_topics_category'), table_name='quick_topics')
    op.drop_table('quick_topics')
    op.drop_index(op.f('ix_qa_cache_entries_normalized_query'), table_name='qa_cache_entries')
    op.drop_index(op.f('ix_qa_cache_entries_id'), table_name='qa_cache_entries')
    op.drop_table('qa_cache_entries')
    op.drop_index(op.f('ix_knowledge_entries_title'), table_name='knowledge_entries')
    op.drop_index(op.f('ix_knowledge_entries_source'), table_name='knowledge_entries')
    op.drop_index(op.f('ix_knowledge_entries_id'), table_name='knowledge_entries')
    op.drop_table('knowledge_entries')
    op.drop_index(op.f('ix_knowledge_blind_spots_status'), table_name='knowledge_blind_spots')
    op.drop_index(op.f('ix_knowledge_blind_spots_normalized_query'), table_name='knowledge_blind_spots')
    op.drop_index(op.f('ix_knowledge_blind_spots_id'), table_name='knowledge_blind_spots')
    op.drop_table('knowledge_blind_spots')
    op.drop_table('faq_entries')
    op.drop_index(op.f('ix_chat_logs_session_id'), table_name='chat_logs')
    op.drop_index(op.f('ix_chat_logs_normalized_query'), table_name='chat_logs')
    op.drop_index(op.f('ix_chat_logs_id'), table_name='chat_logs')
    op.drop_index(op.f('ix_chat_logs_fused_emotion'), table_name='chat_logs')
    op.drop_table('chat_logs')
    op.drop_index(op.f('ix_behavior_summaries_id'), table_name='behavior_summaries')
    op.drop_index(op.f('ix_behavior_summaries_dataset_name'), table_name='behavior_summaries')
    op.drop_table('behavior_summaries')
    op.drop_index(op.f('ix_avatar_configs_is_active'), table_name='avatar_configs')
    op.drop_table('avatar_configs')
    # ### end Alembic commands ###
